# Generated by Django 3.2.16 on 2023-03-01 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpName', models.CharField(max_length=50)),
                ('EmpEmailID', models.CharField(max_length=50)),
                ('EmpPhoneNo', models.IntegerField()),
                ('EmpAddress', models.TextField()),
                ('EmpUsername', models.TextField(max_length=20, unique=True)),
                ('EmpPassword', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobseekerFirstName', models.CharField(max_length=50)),
                ('JobseekerLastName', models.CharField(max_length=50)),
                ('JobseekerGender', models.CharField(max_length=20)),
                ('JobseekerDob', models.CharField(max_length=20)),
                ('JobseekerUsername', models.TextField(max_length=20, unique=True)),
                ('JobseekerPassword', models.TextField(max_length=20)),
                ('JobseekerEmailID', models.CharField(max_length=50)),
                ('JobseekerPhoneNo', models.IntegerField()),
                ('JobseekerSkill', models.TextField()),
                ('JobseekerExperience', models.IntegerField()),
                ('JobseekerTitle', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.TextField()),
                ('JobDesc', models.TextField()),
                ('JobCategory', models.TextField()),
                ('JobSalary', models.IntegerField()),
                ('Jobskill', models.TextField()),
                ('JobStatus', models.BooleanField(default=True)),
                ('EmployerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.employer')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobseekerCover', models.TextField()),
                ('JobseekerResume', models.FileField(upload_to='Resume')),
                ('JobStatus', models.CharField(max_length=50)),
                ('EmployerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.employer')),
                ('JobseekerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.jobseeker')),
            ],
        ),
    ]
