# Generated by Django 3.2.16 on 2023-03-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='JobLocation',
            field=models.TextField(null=True),
        ),
    ]
