# Generated by Django 3.2.16 on 2023-03-04 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_joblisting_joblocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='JobListingID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.joblisting'),
            preserve_default=False,
        ),
    ]
